//! What could go, and how sure we are about it.
//!
//! A treemap shows where the space is; it does not say what is safe to
//! remove. These rules do, for the places that fill Windows disks over and
//! over: caches that rebuild themselves, temporary folders, crash dumps,
//! build output, old installers.
//!
//! Every rule says how confident it is:
//!
//! - [`Safety::Safe`] — regenerated automatically; nothing is lost.
//! - [`Safety::Likely`] — regenerated by rebuilding or reinstalling;
//!   costs time, not data.
//! - [`Safety::Careful`] — the person's own files; only they can say.
//!
//! and what removing means ([`Mode`]): the *contents* of a cache folder, so
//! the application that owns it keeps its folder; the thing *itself*, for
//! build output and old files; or nothing at all, where the right move is
//! an explanation (the hibernation file is not deleted, it is turned off).
//!
//! Rules match on the tree, not on path strings: building a path for each of
//! two million files would cost more than the whole scan.

use std::collections::HashSet;

use ferret_core::Index;

use crate::safety::Policy;
use crate::{Kind, NodeId, Tree};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Safety {
    Safe,
    Likely,
    Careful,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// Empty the folder, keep the folder.
    Contents,
    /// Remove the matched file or folder.
    Itself,
    /// Explain; there is nothing to remove from here.
    Info,
}

/// Case-insensitive path from the volume root; `*` matches one component.
type Pattern = &'static [&'static str];

enum Matcher {
    Paths(&'static [Pattern]),
    /// Folders with this name anywhere under `under`, outermost only —
    /// `node_modules` inside `node_modules` is part of the first one.
    Named {
        names: &'static [&'static str],
        /// A file that must sit beside the folder, e.g. `Cargo.toml` next
        /// to `target`; without it, `target` is just a word.
        beside: Option<&'static str>,
        under: &'static [Pattern],
    },
    /// Files under `under` that have not changed for `days`.
    Stale {
        under: &'static [Pattern],
        days: u64,
        min_size: u64,
        /// Only these extensions, or any when empty.
        extensions: &'static [&'static str],
    },
}

pub struct Rule {
    /// Stable key; the window looks up the title and explanation by it.
    pub id: &'static str,
    pub safety: Safety,
    pub mode: Mode,
    matcher: Matcher,
}

macro_rules! local {
    ($($rest:literal),+) => { &["users", "*", "appdata", "local", $($rest),+] };
}
macro_rules! roaming {
    ($($rest:literal),+) => { &["users", "*", "appdata", "roaming", $($rest),+] };
}

pub static RULES: &[Rule] = &[
    Rule {
        id: "user_temp",
        safety: Safety::Safe,
        mode: Mode::Contents,
        matcher: Matcher::Paths(&[local!("temp")]),
    },
    Rule {
        id: "windows_temp",
        safety: Safety::Safe,
        mode: Mode::Contents,
        matcher: Matcher::Paths(&[&["windows", "temp"]]),
    },
    Rule {
        id: "update_cache",
        safety: Safety::Likely,
        mode: Mode::Contents,
        matcher: Matcher::Paths(&[&["windows", "softwaredistribution", "download"]]),
    },
    Rule {
        id: "browser_cache",
        safety: Safety::Safe,
        mode: Mode::Contents,
        matcher: Matcher::Paths(&[
            local!("google", "chrome", "user data", "*", "cache"),
            local!("google", "chrome", "user data", "*", "code cache"),
            local!("google", "chrome", "user data", "*", "gpucache"),
            local!("microsoft", "edge", "user data", "*", "cache"),
            local!("microsoft", "edge", "user data", "*", "code cache"),
            local!("bravesoftware", "brave-browser", "user data", "*", "cache"),
            local!(
                "bravesoftware",
                "brave-browser",
                "user data",
                "*",
                "code cache"
            ),
            local!("mozilla", "firefox", "profiles", "*", "cache2"),
        ]),
    },
    Rule {
        id: "shader_cache",
        safety: Safety::Safe,
        mode: Mode::Contents,
        matcher: Matcher::Paths(&[
            local!("nvidia", "dxcache"),
            local!("nvidia", "glcache"),
            local!("amd", "dxcache"),
            local!("d3dscache"),
            &["program files (x86)", "steam", "steamapps", "shadercache"],
        ]),
    },
    Rule {
        id: "app_cache",
        safety: Safety::Safe,
        mode: Mode::Contents,
        matcher: Matcher::Paths(&[
            roaming!("code", "cache"),
            roaming!("code", "cacheddata"),
            roaming!("code", "code cache"),
            roaming!("discord", "cache"),
            roaming!("discord", "code cache"),
            roaming!("slack", "cache"),
            roaming!("microsoft", "teams", "cache"),
        ]),
    },
    Rule {
        id: "crash_dumps",
        safety: Safety::Safe,
        mode: Mode::Contents,
        matcher: Matcher::Paths(&[
            local!("crashdumps"),
            &["windows", "minidump"],
            &[
                "programdata",
                "microsoft",
                "windows",
                "wer",
                "reportarchive",
            ],
            &["programdata", "microsoft", "windows", "wer", "reportqueue"],
        ]),
    },
    Rule {
        id: "dev_cache",
        safety: Safety::Likely,
        mode: Mode::Contents,
        matcher: Matcher::Paths(&[
            local!("npm-cache"),
            local!("pip", "cache"),
            local!("yarn", "cache"),
            &["users", "*", ".gradle", "caches"],
        ]),
    },
    Rule {
        id: "node_modules",
        safety: Safety::Likely,
        mode: Mode::Itself,
        matcher: Matcher::Named {
            names: &["node_modules"],
            beside: None,
            under: &[&["users"]],
        },
    },
    Rule {
        id: "build_output",
        safety: Safety::Likely,
        mode: Mode::Itself,
        matcher: Matcher::Named {
            names: &["target"],
            beside: Some("cargo.toml"),
            under: &[&["users"]],
        },
    },
    Rule {
        id: "python_cache",
        safety: Safety::Likely,
        mode: Mode::Itself,
        matcher: Matcher::Named {
            names: &["__pycache__"],
            beside: None,
            under: &[&["users"]],
        },
    },
    Rule {
        id: "recycle_bin",
        safety: Safety::Likely,
        mode: Mode::Info,
        matcher: Matcher::Paths(&[&["$recycle.bin"]]),
    },
    Rule {
        id: "old_installers",
        safety: Safety::Careful,
        mode: Mode::Itself,
        matcher: Matcher::Stale {
            under: &[&["users", "*", "downloads"]],
            days: 90,
            min_size: 1,
            extensions: &["exe", "msi", "msix", "iso", "zip", "rar", "7z"],
        },
    },
    Rule {
        id: "backups",
        safety: Safety::Careful,
        mode: Mode::Itself,
        matcher: Matcher::Named {
            names: &["backup", "backups"],
            beside: None,
            under: &[&["users"]],
        },
    },
    Rule {
        id: "old_big_files",
        safety: Safety::Careful,
        mode: Mode::Itself,
        matcher: Matcher::Stale {
            under: &[&["users"]],
            days: 365,
            min_size: 500 << 20,
            extensions: &[],
        },
    },
    Rule {
        id: "hibernation",
        safety: Safety::Careful,
        mode: Mode::Info,
        matcher: Matcher::Paths(&[&["hiberfil.sys"]]),
    },
    Rule {
        id: "windows_old",
        safety: Safety::Careful,
        mode: Mode::Info,
        matcher: Matcher::Paths(&[&["windows.old"]]),
    },
];

/// What one rule found.
pub struct Suggestion {
    pub rule: &'static Rule,
    /// Matched files or folders; for [`Mode::Contents`], the folders whose
    /// contents would go.
    pub targets: Vec<NodeId>,
    pub bytes: u64,
    pub files: u32,
}

/// FILETIME ticks per day.
const DAY: u64 = 864_000_000_000;

impl Rule {
    /// Whether the rule names exact, reviewed paths. Only such rules may
    /// reach into places the [`Policy`] refuses by hand — Windows' temp
    /// folder, a browser's cache in AppData. Rules that match by name or by
    /// age could match anything, so they get no such trust.
    pub fn is_trusted(&self) -> bool {
        matches!(self.matcher, Matcher::Paths(_))
    }

    /// Whether this rule may offer `node`. An explanation removes nothing,
    /// so it may point anywhere.
    pub fn may_remove(&self, policy: &Policy, node: NodeId) -> bool {
        self.mode == Mode::Info || policy.may_remove(node, self.is_trusted())
    }
}

/// Run every rule over the tree. `now` is a FILETIME; `profile` is the
/// signed-in person's profile folder name. A place matched by an earlier
/// (safer) rule is not offered again by a later one, so the totals can be
/// added up.
pub fn suggest(index: &Index, tree: &Tree, now: u64, profile: &str) -> Vec<Suggestion> {
    let policy = Policy::new(index, tree, profile);
    let mut covered: HashSet<NodeId> = HashSet::new();
    let mut out = Vec::new();

    for rule in RULES {
        let found = match &rule.matcher {
            Matcher::Paths(patterns) => patterns
                .iter()
                .flat_map(|p| resolve(index, tree, p))
                .collect::<Vec<_>>(),
            Matcher::Named {
                names,
                beside,
                under,
            } => named(index, tree, names, *beside, under),
            Matcher::Stale {
                under,
                days,
                min_size,
                extensions,
            } => stale(
                index,
                tree,
                under,
                now.saturating_sub(days * DAY),
                *min_size,
                extensions,
            ),
        };

        let mut targets: Vec<NodeId> = Vec::new();
        for node in found {
            let chain = tree.ancestry(node);
            if chain.iter().any(|n| covered.contains(n)) || !rule.may_remove(&policy, node) {
                continue;
            }
            targets.push(node);
        }
        targets.sort_unstable();
        targets.dedup();
        if targets.is_empty() {
            continue;
        }
        let mut bytes = 0u64;
        let mut files = 0u32;
        for &t in &targets {
            let totals = tree.totals(t);
            bytes += totals.allocated;
            files += totals.files;
        }
        // A few kilobytes is not worth a decision.
        if bytes < 1 << 20 {
            continue;
        }
        if rule.mode != Mode::Info {
            covered.extend(targets.iter().copied());
        }
        targets.sort_by_key(|t| std::cmp::Reverse(tree.totals(*t).allocated));
        out.push(Suggestion {
            rule,
            targets,
            bytes,
            files,
        });
    }
    out
}

/// Every node a pattern names.
fn resolve(index: &Index, tree: &Tree, pattern: Pattern) -> Vec<NodeId> {
    let mut level = vec![tree.root()];
    for segment in pattern {
        let mut next = Vec::new();
        for node in level {
            for &child in tree.children(node) {
                if *segment == "*" || index.name(child as usize).eq_ignore_ascii_case(segment) {
                    next.push(child);
                }
            }
        }
        if next.is_empty() {
            return next;
        }
        level = next;
    }
    level
}

fn roots(index: &Index, tree: &Tree, under: &[Pattern]) -> HashSet<NodeId> {
    under.iter().flat_map(|p| resolve(index, tree, p)).collect()
}

fn named(
    index: &Index,
    tree: &Tree,
    names: &[&str],
    beside: Option<&str>,
    under: &[Pattern],
) -> Vec<NodeId> {
    let roots = roots(index, tree, under);
    let bin: HashSet<NodeId> = resolve(index, tree, &["$recycle.bin"])
        .into_iter()
        .collect();

    let matches: HashSet<NodeId> = (0..tree.root())
        .filter(|n| tree.is_dir(*n) && tree.contains(*n))
        .filter(|n| {
            names
                .iter()
                .any(|name| index.name(*n as usize).eq_ignore_ascii_case(name))
        })
        .filter(|n| match beside {
            None => true,
            Some(file) => tree.parent(*n).is_some_and(|p| {
                tree.children(p)
                    .iter()
                    .any(|s| !tree.is_dir(*s) && index.name(*s as usize).eq_ignore_ascii_case(file))
            }),
        })
        .collect();

    matches
        .iter()
        .copied()
        .filter(|n| {
            let chain = tree.ancestry(*n);
            let above = &chain[..chain.len() - 1];
            above.iter().any(|a| roots.contains(a))
                && !above.iter().any(|a| matches.contains(a) || bin.contains(a))
        })
        .collect()
}

fn stale(
    index: &Index,
    tree: &Tree,
    under: &[Pattern],
    before: u64,
    min_size: u64,
    extensions: &[&str],
) -> Vec<NodeId> {
    let mut out = Vec::new();
    let mut stack: Vec<NodeId> = roots(index, tree, under).into_iter().collect();
    while let Some(node) = stack.pop() {
        for &child in tree.children(node) {
            if tree.is_dir(child) {
                // Hidden application folders are not "files I forgot".
                let name = index.name(child as usize);
                if !name.eq_ignore_ascii_case("appdata") && !name.starts_with('.') {
                    stack.push(child);
                }
                continue;
            }
            let totals = tree.totals(child);
            let name = index.name(child as usize);
            let ext = crate::kinds::extension(name);
            let wanted =
                extensions.is_empty() || extensions.iter().any(|e| ext.eq_ignore_ascii_case(e));
            if wanted
                && totals.allocated >= min_size
                && totals.newest != 0
                && totals.newest < before
                && !matches!(
                    Kind::of(name),
                    Kind::System | Kind::DiskImage | Kind::Database
                )
            {
                out.push(child);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use ferret_core::testing::{dir, file, index_from_specs};
    use ferret_core::ROOT_RECORD;

    const NOW: u64 = 134_000_000_000_000_000; // 2025-08

    fn sample() -> (Index, Tree) {
        let old = NOW - 400 * DAY;
        let index = index_from_specs(vec![
            dir(20, ROOT_RECORD, "Users"),
            dir(21, 20, "pc"),
            dir(22, 21, "AppData"),
            dir(23, 22, "Local"),
            dir(24, 23, "Temp"),
            file(25, 24, "junk.tmp").sized(10 << 20),
            dir(26, 21, "projects"),
            dir(27, 26, "web"),
            dir(28, 27, "node_modules"),
            dir(29, 28, "node_modules"), // nested: part of the outer one
            file(30, 29, "lib.js").sized(1 << 20),
            dir(31, 26, "rusty"),
            file(32, 31, "Cargo.toml").sized(100),
            dir(33, 31, "target"),
            file(34, 33, "app.exe").sized(50 << 20),
            dir(35, 26, "notes"),
            dir(36, 35, "target"), // no Cargo.toml beside it: not build output
            file(37, 36, "plan.txt").sized(1000),
            dir(38, 21, "Downloads"),
            file(39, 38, "setup.exe").sized(80 << 20).modified_at(old),
            file(40, 38, "fresh.exe")
                .sized(80 << 20)
                .modified_at(NOW - DAY),
            file(41, 38, "old-movie.mkv")
                .sized(700 << 20)
                .modified_at(old),
            file(42, ROOT_RECORD, "hiberfil.sys").sized(6 << 30),
            dir(43, ROOT_RECORD, "Windows"),
            file(44, 43, "notepad.exe").sized(1 << 20),
        ]);
        let tree = Tree::build(&index);
        (index, tree)
    }

    fn found<'a>(s: &'a [Suggestion], id: &str) -> Option<&'a Suggestion> {
        s.iter().find(|x| x.rule.id == id)
    }

    fn names(index: &Index, s: &Suggestion) -> Vec<String> {
        let mut n: Vec<String> = s
            .targets
            .iter()
            .map(|t| index.name(*t as usize).to_string())
            .collect();
        n.sort();
        n
    }

    #[test]
    fn temp_is_emptied_not_removed() {
        let (index, tree) = sample();
        let s = suggest(&index, &tree, NOW, "pc");
        let temp = found(&s, "user_temp").expect("temp found");
        assert_eq!(names(&index, temp), ["Temp"]);
        assert_eq!(temp.rule.mode, Mode::Contents);
        assert_eq!(temp.rule.safety, Safety::Safe);
        assert_eq!(temp.files, 1);
    }

    #[test]
    fn only_the_outermost_node_modules_is_offered() {
        let (index, tree) = sample();
        let s = suggest(&index, &tree, NOW, "pc");
        let nm = found(&s, "node_modules").unwrap();
        assert_eq!(nm.targets.len(), 1);
        assert_eq!(tree.totals(nm.targets[0]).files, 1);
    }

    #[test]
    fn target_needs_a_cargo_toml_beside_it() {
        let (index, tree) = sample();
        let s = suggest(&index, &tree, NOW, "pc");
        let build = found(&s, "build_output").unwrap();
        assert_eq!(build.targets.len(), 1);
        assert_eq!(
            tree.path(&index, build.targets[0]),
            r"C:\Users\pc\projects\rusty\target"
        );
    }

    #[test]
    fn stale_rules_look_at_age_size_and_extension() {
        let (index, tree) = sample();
        let s = suggest(&index, &tree, NOW, "pc");
        assert_eq!(
            names(&index, found(&s, "old_installers").unwrap()),
            ["setup.exe"]
        );
        // The movie is old and big but not an installer; the next rule has it.
        assert_eq!(
            names(&index, found(&s, "old_big_files").unwrap()),
            ["old-movie.mkv"]
        );
    }

    #[test]
    fn hibernation_is_explained_not_deleted() {
        let (index, tree) = sample();
        let s = suggest(&index, &tree, NOW, "pc");
        let h = found(&s, "hibernation").unwrap();
        assert_eq!(h.rule.mode, Mode::Info);
        assert_eq!(h.bytes, 6 << 30);
    }

    #[test]
    fn rules_that_find_nothing_are_left_out() {
        let (index, tree) = sample();
        let s = suggest(&index, &tree, NOW, "pc");
        assert!(found(&s, "windows_old").is_none());
        assert!(found(&s, "browser_cache").is_none());
    }

    #[test]
    fn every_rule_id_is_unique() {
        let mut seen = HashSet::new();
        for rule in RULES {
            assert!(seen.insert(rule.id), "duplicate rule id {}", rule.id);
        }
    }
}
